version: '3'

services:

  geekshopping-rabbitmq:
    image: rabbitmq:3-management
    hostname: "geekshopping-rabbitmq"
    labels:
      NAME: "geekshopping-rabbitmq"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - geekshopping
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 10s
        timeout: 10s
        retries: 2

  geekshopping-database:
    image: mariadb:10
    ports:
      - 3341:3306
    environment:
        MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - geekshopping-database:/var/lib/mysql
    networks:
      - geekshopping
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 10s
        retries: 2

  geekshopping-product-api:
    image: geekshopping-product-api
    build:
      context: .
      dockerfile: ProductAPIDockerfile
    ports:
      - 4441:80
    depends_on:
      - geekshopping-database
    networks:
      - geekshopping

  geekshopping-payment-api:
    image: geekshopping-payment-api
    build:
      context: .
      dockerfile: PaymentAPIDockerfile
    ports:
      - 5080:80
    depends_on:
      geekshopping-rabbitmq:
        condition: service_healthy
    networks:
      - geekshopping

  geekshopping-order-api:
    image: geekshopping-order-api
    build:
      context: .
      dockerfile: OrderAPIDockerfile
    ports:
      - 4456:80
    depends_on:
      geekshopping-rabbitmq:
        condition: service_healthy
      geekshopping-database:
        condition: service_healthy
    networks:
      - geekshopping

  geekshopping-email:
    image: geekshopping-email
    build:
      context: .
      dockerfile: EmailDockerfile
    depends_on:
      geekshopping-rabbitmq:
        condition: service_healthy
      geekshopping-database:
        condition: service_healthy
    networks:
      - geekshopping

  geekshopping-coupon-api:
    image: geekshopping-coupon-api
    build:
      context: .
      dockerfile: CouponAPIDockerfile
    ports:
      - 4451:80
    depends_on:
      - geekshopping-database
    networks:
      - geekshopping

  geekshopping-cart-api:
    image: geekshopping-cart-api
    build:
      context: .
      dockerfile: CartAPIDockerfile
    ports:
      - 4446:80
    depends_on:
      - geekshopping-database
    networks:
      - geekshopping

  geekshopping-identity-server:
    image: geekshopping-identity-server
    build:
      context: .
      dockerfile: IdentityServerDockerfile
    ports:
      - 4436:80
    depends_on:
      - geekshopping-database
    networks:
      - geekshopping

  geekshopping-api-gateway:
    image: geekshopping-api-gateway
    build:
      context: .
      dockerfile: APIGatewayDockerfile
    ports:
      - 4481:80
    networks:
      - geekshopping

  geekshopping-web:
    image: geekshopping-web
    build:
      context: .
      dockerfile: WebDockerfile
    ports:
      - 4431:80
    networks:
      - geekshopping
      
networks: 
    geekshopping:
        driver: bridge

volumes:
    geekshopping-database:
        driver: local    